"""Hypothesis deduplicator — detects and merges duplicate hypotheses.

MOD-12.6: Identifies identical or equivalent hypotheses generated by
different modules and merges them to prevent redundant testing.
"""

from __future__ import annotations

__classification__ = "experimental"

import logging
from dataclasses import dataclass, field
from typing import Any

from app.engine.hypothesis_graph import HypothesisGraph, HypothesisNode

logger = logging.getLogger(__name__)


@dataclass
class DeduplicationResult:
    """Result of a deduplication pass."""

    total_before: int = 0
    total_after: int = 0
    duplicates_found: int = 0
    merged_pairs: list[tuple[str, str]] = field(default_factory=list)

    @property
    def reduction_pct(self) -> float:
        if self.total_before == 0:
            return 0.0
        return (self.duplicates_found / self.total_before) * 100

    def to_dict(self) -> dict:
        return {
            "before": self.total_before,
            "after": self.total_after,
            "duplicates": self.duplicates_found,
            "reduction_pct": round(self.reduction_pct, 1),
        }


class HypothesisDeduplicator:
    """Detects and merges duplicate hypotheses.

    Usage::

        dedup = HypothesisDeduplicator()
        result = dedup.deduplicate(hypothesis_graph)
    """

    def deduplicate(self, graph: HypothesisGraph) -> DeduplicationResult:
        """Find and merge duplicate hypotheses."""
        pending = graph.get_pending()
        result = DeduplicationResult(total_before=len(pending))

        # Group by fingerprint
        fingerprints: dict[str, list[HypothesisNode]] = {}
        for node in pending:
            fp = self._fingerprint(node)
            fingerprints.setdefault(fp, []).append(node)

        # Merge duplicates: keep highest confidence, reject others
        for fp, nodes in fingerprints.items():
            if len(nodes) <= 1:
                continue
            # Sort by confidence desc, keep the best
            nodes.sort(key=lambda n: n.confidence, reverse=True)
            best = nodes[0]
            for dup in nodes[1:]:
                graph.reject(dup.hypothesis.hypothesis_id, reason=f"duplicate_of:{best.hypothesis.hypothesis_id}")
                result.duplicates_found += 1
                result.merged_pairs.append((best.hypothesis.hypothesis_id, dup.hypothesis.hypothesis_id))
                # Absorb the best attributes
                best.confidence = max(best.confidence, dup.confidence)
                best.risk_impact = max(best.risk_impact, dup.risk_impact)

        result.total_after = result.total_before - result.duplicates_found
        logger.info("Deduplicator: %d duplicates from %d hypotheses (%.1f%% reduction)",
                     result.duplicates_found, result.total_before, result.reduction_pct)
        return result

    def _fingerprint(self, node: HypothesisNode) -> str:
        """Generate a deduplication fingerprint for a hypothesis."""
        h = node.hypothesis
        # Key: target + tool + vulnerability class (if present)
        vuln_class = h.config.get("vulnerability_class", h.config.get("payload_class", ""))
        test_type = h.config.get("test_type", h.config.get("mutation", ""))
        return f"{h.target_node_id}:{h.tool}:{vuln_class}:{test_type}"
